### ISSUE TITLE
ver@2.11.0 log help msg in wrong format

### ISSUE THREAD

**Issue by donaldshen** [tj/commander.js#663]
should be:
```
  Usage: vue2-init [options]

  Options:

    -h, --help  output usage information

  Examples:
```
instead:
```
  Usage: vue2-init [options]


  Options:

    -h, --help  output usage information
  Examples:
```
btw, ver@2.9.0 is fine
