### ISSUE TITLE
Multiple usages (feature request)

### ISSUE THREAD

**Issue by rstacruz** [tj/commander.js#80]
Calling `.usage()` more than once should allow for something like:

```
  Usage: rebase [-i | --interactive] [options]
  Usage: rebase --continue | --skip | --abort

  Options:

    ...
```
